### ISSUE TITLE
Traduction dans les 23 langues de l'union

### ISSUE THREAD

**Issue by pombredanne** [bzg/licence-gloss#5]
Il serait utile d'offrir une traduction de cette licence dans les 23 langues de l'Union Européenne (les mêmes que la EUPL) car la souveraineté est aussi un problème continental et trans-national. Ces traductions contribueraient éviter la création de d'ilots de contributions exclusivement nationaux. Je veux bien aider pour une traduction en Français.

**Comment by bzg** [comment]
Bonjour, merci pour votre intérêt !  Notez qu'à ce jour il n'y a pas de licence écrite (donc pas de licence à traduire) et que ce projet n'est qu'une spéculation personnelle - j'ai mis à jour le README.org pour qu'il précise bien cela.

**Comment by bzg** [comment]
Au fait : ce dépôt était en réalité un poisson d'avril... auquel je me suis moi-même laissé prendre (de façon intéressante.)

Je laisse la nouvelle présentation, pour les générations futures, qui pourront rire ou le prendre au sérieux.
